# Generated by Django 3.2.5 on 2023-09-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_tokenotp_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenotp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
